export { default as IExecutable } from './executable.interface'
export { default as IUndoable } from './undoable.interface'
export { default as IStartable } from './startable.interface'
export { default as IStoppable } from './stoppable.interface'
export { default as IResettable } from './resettable.interface'
export { default as ICanSetCommand } from './can-set-command.interface'
